apiVersion: v1
kind: Service
metadata:
  name: demoapp-lb
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: demoapp          # must match your Deployment labels
  ports:
    - name: http
      port: 80            # external port
      targetPort: 3000      # container port
      protocol: TCP
